num_batches: 170000
val_interval: 5000
val_mult: 4
batch_size: 32
length: 256
embedding_dim: 256
depth: 12
heads: 4
hidden_mult: 4
lr: 0.0003
warmup_steps: 5000
start_factor: 0.1
sampling: false
sample_length: 256
temperature: 0.5
save: true
save_path: null
load: false
load_path: null
seed: -1
final: false
grad_vis: false
visualize: false